name: Main workflow
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install psql client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Wait for DB
        run: |
          for i in $(seq 1 60); do
            PGPASSWORD="${{ secrets.DB_PASSWORD }}" \
            psql "postgresql://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}" \
              -c 'select 1' && exit 0
            sleep 2
          done
          echo "DB is not reachable" >&2
          exit 1

      - name: Flyway migrate via Docker
        run: |
          docker run --rm \
            -v "${{ github.workspace }}/migrations:/flyway/sql:ro" \
            flyway/flyway:10 \
            -url="jdbc:postgresql://${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}" \
            -user="${{ secrets.DB_USER }}" \
            -password="${{ secrets.DB_PASSWORD }}" \
            -locations="filesystem:/flyway/sql" \
            -schemas="public" \
            -connectRetries=30 \
            -cleanDisabled=true \
            migrate

      - name: Download and setup autotests binaries
        run: |
          wget -qO- cloud-services-engineer.gitlab.yandexcloud.net/practicum-cloud-services/dbops-autotests/-/package_files/1/download > dbopstest
          chmod +x ./dbopstest
          sudo mv ./dbopstest /usr/local/bin/dbopstest

      - name: Test
        run: |
          dbopstest \
            -test.v \
            -host=${{ secrets.DB_HOST }} \
            -port=${{ secrets.DB_PORT }} \
            -user=${{ secrets.DB_USER }} \
            -password=${{ secrets.DB_PASSWORD }} \
            -db=${{ secrets.DB_NAME }}
