name: Main workflow
on:
  push:
    branches:
      - main

concurrency:
  group: migrate-${{ github.ref }}
  cancel-in-progress: true

jobs:
  migrate:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Flyway-миграции
      - name: Install psql client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
      - name: Wait for DB
        run: |
          for i in $(seq 1 60); do
            PGPASSWORD="$DB_PASSWORD" psql "postgresql://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME" -c 'select 1' && exit 0
            sleep 2
          done
          echo "DB is not reachable" >&2
          exit 1
      - name: Flyway migrate
        uses: flyway/flyway-action@v3
        with:
          url: jdbc:postgresql://${{ env.DB_HOST }}:${{ env.DB_PORT }}/${{ env.DB_NAME }}
          user: ${{ env.DB_USER }}
          password: ${{ env.DB_PASSWORD }}
          locations: filesystem:migrations
          schemas: public
          cleanDisabled: true
          connectRetries: 30

      # Этот шаг оставьте без изменений
      - name: Download and setup autotests binaries
        run: |
          wget -qO- cloud-services-engineer.gitlab.yandexcloud.net/practicum-cloud-services/dbops-autotests/-/package_files/1/download > dbopstest
          chmod +x ./dbopstest
          mv ./dbopstest /usr/local/bin/dbopstest

      # Этот шаг оставьте без изменений
      - name: Test
        run: |
          dbopstest \
            -test.v \
            -host=${{ env.DB_HOST }} \
            -port=${{ env.DB_PORT }} \
            -user=${{ env.DB_USER }} \
            -password=${{ env.DB_PASSWORD }} \
            -db=${{ env.DB_NAME }}
